datadir: .

# Logging.
#
# Per-module log levels are defined below. If you prefer just one unified log
# level, you can use:
#
# log:
#   level: debug
log:
  level:
    # Per-module log levels. Longest prefix match will be taken. Fallback to
    # "default", if no match.
    default: info
    tendermint: warn
    tendermint/context: error
  format: JSON
  # By default logs are output to stdout. If you would like to output logs to
  # a file, you can use:
  #
  # file: /var/log/oasis-node.log
  file: ./node.log

debug:
  dont_blame_oasis: true
  allow_root: true
  allow_test_keys: true
  rlimit: 50000
  crash:
    default: 0.000000
  allow_debug_enclaves: true

# Genesis.
genesis:
  # Path to the genesis file for the current version of the network.
  file: ../genesis.json

# Worker configuration.
worker:
  sentry:
    # Enable sentry node.
    enabled: true
    # Port used by validator nodes to query sentry node for registry
    # information.
    # IMPORTANT: Only validator nodes protected by the sentry node should have
    # access to this port. This port should not be exposed on the public
    # network.
    control:
      port: 20030
      authorized_pubkey:
        - aVn/lv4gNjRuLH7xIihvT6UeQt2K9weyHtWMZaKHW8M=
grpc:
  log:
    debug: true

# Consensus backend.
consensus:
  # Tendermint backend configuration.
  tendermint:
    core:
      listen_address: tcp://0.0.0.0:20015
      external_address: tcp://192.168.14.95:20015
  
    abci:
      prune:
        strategy: keep_n
        # Keep ~1 hour of data since block production is ~1 block every 6 seconds.
        # (3600/6 = 600)
        num_kept: 600
    # List of seed nodes to connect to.
    # NOTE: You can add additional seed nodes to this list if you want.
    p2p:
      seed:
        - "D54FE0256DEE02C42591ADFCB83940F09A9B808D@192.168.14.9:20000"
    sentry:
      upstream_address:
        - "5A6815B973E2E7D41F7A029F397EF5E1AE850960@127.0.0.1:20012"
    debug:
      addr_book_lenient: true
      allow_duplicate_ip: true
    upgrade:
      stop_delay: 10s
