datadir: .
log:
  level:
    default: debug
    tendermint: warn
    tendermint/context: error
  format: JSON
  file: ./node.log
debug:
  dont_blame_oasis: true
  allow_root: true
  allow_test_keys: true
  rlimit: 50000
  crash:
    default: 0.0
  allow_debug_enclaves: true
genesis:
  file: ../genesis.json
worker:
  registration:
    rotate_certs: 1
    entity: ../entity-01/entity.json
grpc:
  log:
    debug: true
consensus:
  validator: true
  tendermint:
    core:
      listen_address: tcp://0.0.0.0:20001
      external_address: tcp://13.213.177.51:20001
    min_gas_price: 0
    submission:
      gas_price: 0
    abci:
      prune:
        strategy: none
    supplementarysanity:
      enabled: true
      interval: 1
    p2p:
      seed:
        - 9F0C9F27607CFA451223BC56A2D789B4D56EEF8B@13.213.177.51:20000
        - A9545A8BE685814E10BBFDBA14A64E83A05E54A6@13.214.27.191:20000
    debug:
      addr_book_lenient: true
      allow_duplicate_ip: true
    upgrade:
      stop_delay: 10s
