datadir: .
log:
  level:
    default: info
    tendermint: warn
    tendermint/context: error
  format: JSON
  file: ./node.log
debug:
  dont_blame_oasis: true
  allow_root: true
  allow_test_keys: true
  rlimit: 50000
  crash:
    default: 0.0
  allow_debug_enclaves: true
genesis:
  file: ../genesis.json
worker:
  p2p:
    port: 20100
    addresses:
      - 54.151.252.179:20100
runtime:
  mode: client
  provisioner: unconfined
  paths:
    - ../runtime-hela-evm/hela-evm-runtime-1-0-6.orc
    - ../runtime-hela-evm/hela-evm-runtime-1-0-7.orc
  config:
    00000000000000000000000000000000000000000000000064884141bb9ca059:
      allow_expensive_queries: true
grpc:
  log:
    debug: true
consensus:
  tendermint:
    core:
      listen_address: tcp://0.0.0.0:20000
      external_address: tcp://54.151.252.179:20000
    abci:
      prune:
        strategy: none
    p2p:
      seed:
        - 9F0C9F27607CFA451223BC56A2D789B4D56EEF8B@13.213.177.51:20000
        - A9545A8BE685814E10BBFDBA14A64E83A05E54A6@13.214.27.191:20000
    debug:
      addr_book_lenient: true
      allow_duplicate_ip: true
    upgrade:
      stop_delay: 10s
